modLoader = "javafml"
loaderVersion = "[47,)"
license = "${license}"
clientSideOnly = true
[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
displayURL = "https://github.com/AvenLabs-Co/Smooth-Thai"
logoFile = "${mod_id}.png"
authors = "${mod_author}"
description = '''${description}'''
[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
